import { icon } from './icons.js';
import { inPeriod, overview, exerciseOptions, availableSides, exerciseSeries } from './progress.js';
const escape = (value) => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const number = (value) => Number(value).toLocaleString('es-CO', { maximumFractionDigits: 2 });
const date = (value) => new Date(value).toLocaleDateString('es-CO', { day: 'numeric', month: 'short' });
const sideNames = { both: 'Sin lado asignado', left: 'Izquierdo', right: 'Derecho' };
const metrics = (stats) => `<div class="overview-metrics"><div><strong>${stats.sessions}</strong><span>Entrenamientos</span></div><div><strong>${stats.sets}</strong><span>Series hechas</span></div><div><strong>${stats.days}</strong><span>Días activos</span></div></div>`;

export function homeDashboard(sessions) {
  const stats = overview(inPeriod(sessions, 7));
  const last = sessions[0];
  return `<div class="home-intro"><p class="eyebrow">TU ESPACIO DE ENTRENAMIENTO</p><h2>Cada sesión cuenta.</h2><p>Registra hoy. Mira cómo avanzas.</p></div><button class="new-session-card" data-action="new-session"><span><strong>Crear entrenamiento</strong><small>Empieza con un ejercicio y sigue a tu ritmo</small></span><i>${icon('plus')}</i></button><section class="dashboard-card"><div class="card-heading"><h2>Últimos 7 días</h2><button data-view="progress" aria-label="Ver progreso">${icon('chart')}</button></div>${metrics(stats)}</section><section class="home-recent"><div class="card-heading"><h2>Último entrenamiento</h2><button data-view="history">Ver historial</button></div>${last ? `<button class="recent-session" data-history-session="${escape(last.id)}"><div><small>${date(last.startedAt)}</small><strong>${escape(last.label)}</strong><p>${escape(last.entries.map((entry) => entry.exercise).join(' · '))}</p></div>${icon('right')}</button>` : `<div class="quiet-empty"><strong>Tu historia empieza aquí</strong><p>Completa tu primer entrenamiento para ver aquí tu actividad y progreso.</p></div>`}</section>`;
}

function chart(points) {
  const w = 320, h = 160, x0 = 42, x1 = 302, y0 = 16, y1 = 130;
  const max = Math.ceil(Math.max(1, ...points.map((point) => point.weight)) / 10) * 10;
  const first = +new Date(points[0].date), last = +new Date(points.at(-1).date);
  const x = (point, index) => last !== first ? x0 + ((+new Date(point.date) - first) / (last - first)) * (x1 - x0) : x0 + index * (x1 - x0) / Math.max(1, points.length - 1);
  const y = (point) => y1 - point.weight / max * (y1 - y0);
  const line = points.map((point, index) => `${x(point, index)},${y(point)}`).join(' ');
  return `<svg class="progress-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Carga máxima registrada por entrenamiento, en libras. Los valores están en la tabla inferior.">${[0, .5, 1].map((fraction) => `<line x1="${x0}" x2="${x1}" y1="${y1 - fraction * (y1 - y0)}" y2="${y1 - fraction * (y1 - y0)}" class="chart-grid"/><text x="${x0 - 7}" y="${y1 - fraction * (y1 - y0) + 4}" text-anchor="end">${number(max * fraction)}</text>`).join('')}<polyline points="${line}" fill="none" class="chart-line"/>${points.map((point, index) => `<circle cx="${x(point, index)}" cy="${y(point)}" r="3.5" class="chart-dot"><title>${date(point.date)}: ${number(point.weight)} lb, ${point.reps} reps</title></circle>`).join('')}<text x="${x0}" y="154">${date(points[0].date)}</text><text x="${x1}" y="154" text-anchor="end">${date(points.at(-1).date)}</text></svg>`;
}

export function progressDashboard(sessions, state) {
  const filtered = inPeriod(sessions, state.progressPeriod || '90');
  const options = exerciseOptions(sessions);
  if (!options.some((option) => option.id === state.progressExercise)) state.progressExercise = options[0]?.id || '';
  const sides = availableSides(sessions, state.progressExercise);
  if (!sides.includes(state.progressSide)) state.progressSide = sides[0] || 'both';
  const points = exerciseSeries(filtered, state.progressExercise, state.progressSide);
  const latest = points.at(-1), prior = points.at(-2);
  return `<div class="page-title compact-title"><p class="eyebrow">TU CONSTANCIA, A LA VISTA</p><h2>Progreso</h2><p>Un vistazo a tu actividad y a cada ejercicio.</p></div><div class="period-filter" aria-label="Periodo de análisis">${[['30', '30 días'], ['90', '90 días'], ['all', 'Todo']].map(([id, label]) => `<button data-period="${id}" aria-pressed="${(state.progressPeriod || '90') === id}">${label}</button>`).join('')}</div>${metrics(overview(filtered))}<section class="dashboard-card progress-detail"><div class="card-heading"><h2>Por ejercicio</h2>${icon('chart')}</div>${options.length ? `<label class="field-label">Ejercicio<select id="progress-exercise">${options.map((option) => `<option value="${escape(option.id)}" ${state.progressExercise === option.id ? 'selected' : ''}>${escape(option.name)}</option>`).join('')}</select></label>${sides.length > 1 || sides[0] !== 'both' ? `<label class="field-label">Registro<select id="progress-side">${sides.map((side) => `<option value="${side}" ${state.progressSide === side ? 'selected' : ''}>${sideNames[side]}</option>`).join('')}</select></label>` : ''}${latest ? `<div class="load-summary"><div><small>Última carga máxima</small><strong>${number(latest.weight)} <span>lb</span></strong><p>${latest.reps} reps con esa carga · ${date(latest.date)}</p></div><div class="load-change"><small>Frente a la anterior</small><strong>${prior ? `${latest.weight - prior.weight > 0 ? '+' : ''}${number(latest.weight - prior.weight)} lb` : 'Sin comparación'}</strong></div></div>${points.length > 1 ? chart(points) : `<p class="quiet-empty">Ya tienes tu primer registro. La gráfica aparecerá al completar otra sesión con este ejercicio y tipo de registro.</p>`}<p class="chart-note">La gráfica muestra la mayor carga de una serie completada en cada sesión. Más peso no implica por sí solo más progreso: revisa también las repeticiones y mantén la misma forma de registrar la carga.</p><details class="progress-records"><summary>Ver registros (${points.length})</summary><table><caption class="visually-hidden">Carga máxima y repeticiones de esa misma serie</caption><thead><tr><th>Fecha</th><th>Peso</th><th>Reps</th></tr></thead><tbody>${[...points].reverse().map((point) => `<tr><td>${date(point.date)}</td><td>${number(point.weight)} lb</td><td>${point.reps}</td></tr>`).join('')}</tbody></table></details>` : `<div class="quiet-empty"><strong>Sin registros en este periodo</strong><p>Prueba otro periodo o completa una sesión con este ejercicio.</p></div>`}` : `<div class="quiet-empty"><strong>Tu progreso empieza con una sesión</strong><p>Cuando registres un entrenamiento, podrás explorar aquí tus cargas por ejercicio. Los borradores no cuentan.</p><button class="text-link" data-action="new-session">Crear entrenamiento</button></div>`}</section><p class="chart-note">Solo entrenamientos finalizados. Las series por lado cuentan una vez si al menos un lado está completado. Los registros sin lado se analizan por separado.</p>`;
}

export function settingsDashboard(settings, sessions, customCount) {
  return `<div class="page-title compact-title"><p class="eyebrow">A TU MANERA</p><h2>Ajustes</h2><p>Tu forma de registrar. Tus datos bajo control.</p></div><section class="dashboard-card"><div class="card-heading"><h2>Cómo entrenas</h2>${icon('edit')}</div><p class="section-description">Modo de registro para los próximos entrenamientos. La sesión actual conserva su modo.</p><div class="mode-options">${[['exercise', 'Por ejercicio', 'Edita las series y guárdalas juntas.'], ['set', 'Por serie', 'Marca cada serie o lado al terminar.']].map(([id, label, copy]) => `<button data-mode="${id}" aria-pressed="${settings.trackingMode === id}"><span class="mode-indicator">${settings.trackingMode === id ? icon('check') : ''}</span><span><strong>${label}</strong><small>${copy}</small></span></button>`).join('')}</div></section><section class="dashboard-card"><div class="card-heading"><h2>Tu biblioteca</h2>${icon('history')}</div><div class="library-summary"><span><strong>${sessions.length}</strong> entrenamientos</span><span><strong>${customCount}</strong> ejercicios propios</span></div><p class="section-description">Se guarda en este navegador. Exporta una copia para conservarla fuera del dispositivo.</p><div class="backup-actions"><button data-action="export"><strong>Exportar copia</strong><small>Guardar un archivo JSON</small>${icon('right')}</button><button data-action="import"><strong>Restaurar copia</strong><small>Reemplaza los datos actuales</small>${icon('right')}</button></div></section><details class="danger-settings"><summary>Administrar borrado</summary><p>Elimina historial, sesión activa, ejercicios propios y preferencias de este navegador.</p><button data-action="clear-data">Borrar todos los datos</button></details><p class="version">Sterk · Versión 1.4<br>Hecho para entrenar a tu ritmo.</p>`;
}
